spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true
server:
  server-header: Spring Boot 2.7.17, Tomcat 9.0.82
  servlet:
    context-path: "/bad-example"
  port: 8081